-- HeelsUp Migration 0010 — Seed Default CMS Pages
-- Run: npx wrangler d1 execute heelsup-live --file=migrations/0010_seed_pages.sql
-- Run: npx wrangler d1 execute heelsup-live --remote --file=migrations/0010_seed_pages.sql

INSERT OR IGNORE INTO pages (title, slug, content, meta_title, meta_description, active, created_at, updated_at) VALUES
('Privacy Policy', 'privacy-policy', '<h3>1. Collection of Information</h3><p>We collect information when you register on our site, place an order, or subscribe to our newsletter.</p><h3>2. Use of Information</h3><p>Any of the information we collect from you may be used to personalize your experience, improve our website, improve customer service, and process transactions.</p><h3>3. Data Protection</h3><p>We implement a variety of security measures to maintain the safety of your personal information when you place an order or enter, submit, or access your personal info.</p>', 'Privacy Policy - HeelsUp', 'Privacy policy and data protection terms for HeelsUp customers.', 1, datetime('now'), datetime('now')),

('Terms & Conditions', 'terms-and-conditions', '<h3>1. Agreement to Terms</h3><p>By accessing our website, you agree to be bound by these terms and conditions, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws.</p><h3>2. Use License</h3><p>Permission is granted to temporarily download one copy of the materials (information or software) on HeelsUp website for personal, non-commercial transitory viewing only.</p><h3>3. Disclaimer</h3><p>The materials on HeelsUp website are provided on an ''as is'' basis. HeelsUp makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability.</p>', 'Terms & Conditions - HeelsUp', 'Terms and conditions of service for HeelsUp.', 1, datetime('now'), datetime('now')),

('Exchange & Returns Policy', 'returns', '<h3>Easy Exchange & Returns</h3><p>We want you to love your HeelsUp purchase! If you need to exchange or return an item, please read our policy below.</p><h3>7-Day Exchange Window</h3><p>We accept exchanges on all products within 7 days of delivery. Items must be unworn, undamaged, and in their original packaging with tags intact.</p><h3>Exchange Process</h3><p>To request an exchange, go to your Profile -> Orders -> Request Exchange, or contact our support team. We will arrange a reverse pickup for you.</p>', 'Exchange & Returns Policy - HeelsUp', 'Information about easy 7-day exchange and returns policy.', 1, datetime('now'), datetime('now')),

('Shipping Information', 'shipping-info', '<h3>Fast & Secure Shipping</h3><p>We deliver to over 20,000+ pincodes across India.</p><h3>Delivery Time</h3><p>Most orders are processed within 24-48 hours and delivered within 3-5 business days. Express shipping is available for select pincodes with 1-2 day delivery.</p><h3>Free Shipping</h3><p>We offer FREE standard shipping on all orders above ₹799. For orders below ₹799, a flat shipping charge of ₹60 is applicable.</p>', 'Shipping & Delivery Info - HeelsUp', 'Shipping times, rates, and delivery information.', 1, datetime('now'), datetime('now')),

('Frequently Asked Questions', 'faq', '<h3>Q: What payment options do you support?</h3><p>We support all major payment options including UPI, Credit/Debit cards, Net Banking, and Wallet payments via Razorpay.</p><h3>Q: How can I track my order?</h3><p>Once your order is shipped, you will receive a tracking link via SMS/email. You can also track your order directly on our website using the "Track Order" link in the footer.</p><h3>Q: What is your size guide?</h3><p>Please refer to our Size Guide link in the footer for detailed measurements. We recommend buying your standard UK/India shoe size.</p>', 'FAQs - HeelsUp', 'Frequently asked questions about ordering, payments, and shipping.', 1, datetime('now'), datetime('now')),

('About HeelsUp', 'about', '<h3>Welcome to HeelsUp</h3><p>HeelsUp is India''s premier online destination for luxury women''s footwear. Designed in Jodhpur, our mission is to create stunning, high-quality heels, flats, sandals, wedges, and bags that make you feel confident and elegant.</p><h3>Our Quality Promise</h3><p>We use premium materials and handcraft each pair to ensure maximum comfort and durability, so you can stand tall and comfortable all day long.</p>', 'About HeelsUp', 'Our story, design philosophy, and quality commitment.', 1, datetime('now'), datetime('now')),

('Size Guide', 'size-guide', '<h3>Find Your Perfect Fit</h3><p>Buying shoes online can be tricky, so we''ve put together this size guide to help you find the perfect fit.</p><table border="1" cellpadding="5" style="border-collapse: collapse; text-align: center; width: 100%;"><thead><tr style="background: #f7f5f0;"><th>UK/India Size</th><th>EU Size</th><th>Foot Length (cm)</th></tr></thead><tbody><tr><td>3</td><td>36</td><td>22.5</td></tr><tr><td>4</td><td>37</td><td>23.0</td></tr><tr><td>5</td><td>38</td><td>23.8</td></tr><tr><td>6</td><td>39</td><td>24.6</td></tr><tr><td>7</td><td>40</td><td>25.1</td></tr><tr><td>8</td><td>41</td><td>25.4</td></tr></tbody></table>', 'Size Guide - HeelsUp', 'Find your perfect size with our detailed shoe measurement chart.', 1, datetime('now'), datetime('now'));
