ALTER TABLE users ADD COLUMN staff_permissions TEXT DEFAULT '[]';
ALTER TABLE users ADD COLUMN is_blocked INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN last_login_at TEXT;
ALTER TABLE users ADD COLUMN total_orders INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN total_spent REAL NOT NULL DEFAULT 0;
